### PR TITLE
Amp 1888

### PR DESCRIPTION
**Pull request by bdwheele**
Package Prototype

### CODE REVIEW

**Review by yingfeng-iu — COMMENTED** [review]
why is applause-detection in gitignore? what about other container MGMs?

**Comment by bdwheele** [comment]
The gitignore entries for tools/<mgm-package>/<mgm-like-name>  are because those are submodules and I don't want files generated or modified in those other repos to be reflected in the amp_mgms repository.

**Comment by bdwheele** [comment]
Ugh, it ate my path:
tools/mgm package name/git repo for the mgm's core

**Comment by yingfeng-iu** [comment]
do you want to add other submodules to the .gitignore as well?

**Review by yingfeng-iu — APPROVED** [review]

**Comment by bdwheele** [comment]
The .gitignore seems to be correct from what I can see.

**Pull request closed without merging**
